import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  mcApi: [
    "mc-api/index",
    "mc-api/available-endpoints",
    {
      type: "category",
      label: "Advanced",
      items: [
        "mc-api/Advanced/naming-convention",
        "mc-api/Advanced/unusual-item-names",
      ],
      link: {
        type: "generated-index",
        slug: "/mc-api/advanced",
      },
    },
  ],

  petarLib: [
    "petarlib/index",
    "petarlib/installation",
    "petarlib/building-from-source",
    {
      type: "category",
      label: "Development",
      items: [
        "petarlib/development/setup",
        "petarlib/development/javadocs",
        "petarlib/development/logging",
        "petarlib/development/chat",
        "petarlib/development/net",
        "petarlib/development/task",
        "petarlib/development/notifications",
      ],
       link: {
            type: "generated-index",
            slug: "/petarlib/development",
          },
    },
  ],

  fishTracker: [
    "fish-tracker/index",
    "fish-tracker/getting-started",
    "fish-tracker/rarity-tiers",
    {
      type: "category",
      label: "Backend",
      items: [
        "fish-tracker/backend/introduction",
        "fish-tracker/backend/installation-and-deployment",
        "fish-tracker/backend/models",
        {
          type: "category",
          label: "API Docs",
          items: [
            "fish-tracker/backend/api/reference",
            "fish-tracker/backend/api/overview",
            "fish-tracker/backend/api/rate-limiter",
            "fish-tracker/backend/api/public",
            "fish-tracker/backend/api/admin",
          ],
          link: {
            type: "generated-index",
            slug: "/fish-tracker/backend/api",
          },
        },
      ],
      link: {
        type: "generated-index",
        slug: "/fish-tracker/backend",
      },
    },
    {
      type: "category",
      label: "Frontend",
      items: [
        "fish-tracker/frontend/introduction",
        "fish-tracker/frontend/architecture",
        "fish-tracker/frontend/development-and-deployment",
      ],
      link: {
        type: "generated-index",
        slug: "/fish-tracker/frontend",
      },
    },
    {
      type: "category",
      label: "App",
      items: [
        "fish-tracker/app/intro",
        "fish-tracker/app/installation",
        "fish-tracker/app/usage",
        "fish-tracker/app/security",
        "fish-tracker/app/build",
        "fish-tracker/app/supported-patterns",
      ],
      link: {
        type: "generated-index",
        slug: "/fish-tracker/app",
      },
    },
  ],

  fishTrackerMod: [
    "fish-tracker/mod/index",
    "fish-tracker/mod/installation",
    "fish-tracker/mod/configuration",
    "fish-tracker/mod/usage",
    "fish-tracker/mod/features",
    "fish-tracker/mod/building-from-source",
    "fish-tracker/mod/dependencies",
  ],

  durationParser: [
    "duration-parser/index",
    "duration-parser/installation",
    "duration-parser/usage",
    "duration-parser/examples",
  ],

  petarLib_bukkit: [
    "petarlib-bukkit/index",
    "petarlib-bukkit/building-from-source",
    {
      type: "category",
      label: "Development",
      items: [
        "petarlib-bukkit/development/setup",
        "petarlib-bukkit/development/javadocs",
        "petarlib-bukkit/development/net",
        "petarlib-bukkit/development/task",
        "petarlib-bukkit/development/notifications",
      ],
       link: {
            type: "generated-index",
            slug: "/petarlib-bukkit/development",
          },
    },
  ],
};

export default sidebars;
